export const SET_STORAGE_TYPE = 'SET_STORAGE_TYPE';

export const SET_FILE_STORAGE_CONFIG = 'SET_FILE_STORAGE_CONFIG';

export const SET_MYSQL_CONFIG = 'SET_MYSQL_CONFIG';

export const SET_SERVER_CONFIG = 'SET_SERVER_CONFIG';
