export const SET_STORAGE_TYPE = 'SET_STORAGE_TYPE';

export const SET_FILE_STORAGE_CONFIG = 'SET_FILE_STORAGE_CONFIG';

export const SET_MYSQL_CONFIG_LOCALHOST = 'SET_MYSQL_CONFIG_LOCALHOST';

export const SET_MYSQL_CONFIG_PORT = 'SET_MYSQL_CONFIG_PORT';

export const SET_MYSQL_CONFIG_USERNAME = 'SET_MYSQL_CONFIG_USERNAME';

export const SET_MYSQL_CONFIG_PASSWORD = 'SET_MYSQL_CONFIG_PASSWORD';

export const SET_MYSQL_CONFIG_DATABASE = 'SET_MYSQL_CONFIG_DATABASE';

export const SET_SERVER_CONFIG_DASHBOARD_PORT = 'SET_SERVER_CONFIG_DASHBOARD_PORT';

export const SET_SERVER_CONFIG_PORTAL_PORT = 'SET_SERVER_CONFIG_PORTAL_PORT';
